### ISSUE TITLE
Fix initial README.md generated by canvas init

### ISSUE THREAD

**Issue by andhines** [canvas-medical/canvas-plugins#113]
The formatting is not good, see e.g. https://github.com/Medical-Software-Foundation/canvas/tree/main/protocols/rx_search_result_price_annotation_example

<img width="1223" alt="image" src="https://github.com/user-attachments/assets/57d3370e-dc1a-4d43-816a-e80beb1e3177">

**Comment by aduane** [comment]
Fixed in #102
